-- DELETE/TRUNCATE in reverse dependency order

TRUNCATE task_completions RESTART IDENTITY CASCADE;
TRUNCATE list_signoffs RESTART IDENTITY CASCADE;
TRUNCATE task_overrides RESTART IDENTITY CASCADE;
TRUNCATE list_instance_assignees RESTART IDENTITY CASCADE;
TRUNCATE list_instance_managers RESTART IDENTITY CASCADE;
TRUNCATE list_instances RESTART IDENTITY CASCADE;
TRUNCATE task_list_tasks RESTART IDENTITY CASCADE;
TRUNCATE task_lists RESTART IDENTITY CASCADE;
TRUNCATE template_tasks RESTART IDENTITY CASCADE;
TRUNCATE template_lists RESTART IDENTITY CASCADE;
TRUNCATE center_memberships RESTART IDENTITY CASCADE;
TRUNCATE rooms RESTART IDENTITY CASCADE;
TRUNCATE centers RESTART IDENTITY CASCADE;
TRUNCATE groups RESTART IDENTITY CASCADE;
